on:
  schedule:
    # Trigger the sync every 10 minutes.
    - cron: '*/10 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    environment: Cron
    steps:
      - name: Check out the repo itself
        uses: actions/checkout@v3
        with:
          path: config

      - name: Restore sync cache folder
        uses: actions/cache@v3
        with:
          path: cache
          # We don't really need a cache key as we never want to throw the cache
          # away.
          key: ${{ runner.os }}

      - name: Check if cache files are there
        run: ls -la cache

      - name: Install GPG to decrypt the configuration file
        run: sudo apt-get update && sudo apt-get install -y gnupg

      - name: Decrypt the configuration file
        run: cd config && gpg --batch --yes --decrypt --passphrase="$GPG_PASSPHRASE" --decrypt mastodon-twitter-sync.toml.gpg > mastodon-twitter-sync.toml
        env:
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Download latest mastodon-twitter-sync executable
        uses: robinraju/release-downloader@v1.6
        with:
          repository: "klausi/mastodon-twitter-sync"
          latest: true
          fileName: "mastodon-twitter-sync-x86_64-unknown-linux-gnu.tar.gz"

      - name: Execute sync
        run: cd cache && ../mastodon-twitter-sync --config=../config/mastodon-twitter-sync.toml
